### ISSUE TITLE
Errro validating natspec comments for  functions

### ISSUE THREAD

**Issue by jsperezg** [ZeppelinSolutions/solium-plugin-zeppelin#29]
When  I don't add the comment /// @title ...  for any of my contract  functions  the linter  complains. However, with it  added  tests fail due to compile errors:

DocstringParsingError: Doc tag @title not valid for functions.

What i'm doing wrong?

**Comment by mgregson** [comment]
This looks fixed in https://github.com/OpenZeppelin/solium-plugin-zeppelin/commit/4a0698813fd0a9b73032fd69cf684c5510211454, but it hasn't been released yet.

Could we get this tagged and released?

**Comment by come-maiz** [comment]
Hey @jsperezg and @mgregson. I'm sorry to inform you that I'm deprecating this package, so I'm closing this as won't fix. More info in the [README](https://github.com/ZeppelinSolutions/solium-plugin-zeppelin#deprecated).
