### ISSUE TITLE
[Fatal error] No such rule exists: all-state-variables-private

### ISSUE THREAD

**Issue by mattaereal** [ZeppelinSolutions/solium-plugin-zeppelin#36]
Everything works like a charm except for that rule. Haven't looked into it, letting you guys know.

Thanks :)

`✖ [Fatal error] An error occurred while linting over contract.sol: "zeppelin/all-state-variables-private" - No such rule exists.`

If I take it out, the others work well.

**Comment by bkiac** [comment]
If you install from npm, that package links to the https://github.com/elopio/solium-plugin-zeppelin repository, which doesn't have the `zeppelin/all-state-variables-private` rule. The npm package should link to this repository instead.

**Comment by come-maiz** [comment]
Hey @mattaereal and @bkiac. I'm sorry to inform you that I'm deprecating this package, so I'm closing this as won't fix. More info in the [README](https://github.com/ZeppelinSolutions/solium-plugin-zeppelin#deprecated).
